### ISSUE TITLE
Preserving point in fill-paragraph

### ISSUE THREAD

**Issue by ixtenu** [japanoise/gomacs#29]
`doFillParagraph` moves point (the cursor) to the end of the filled paragraph.  It would be nice if Gomacs left point where it was, so that `M-q` could be used without losing your place.

I have a tentative implementation of this on a branch ([fill-preserve-point-wip](https://github.com/japanoise/gomacs/compare/master...ixtenu:fill-preserve-point-wip)).  It seems to work, but I haven't submitted a PR because it makes an assumption about `FillString` that I'm not sure it should make.  Namely, it assumes that the number of "words" (e.g., tokens separated by spaces or newlines) will be the same both before and after `FillString`.  That's true currently, but if `FillString` were to be later enhanced to support source code comments then that would no longer work (e.g., for C99 style comments, the number of `//` "words" could change).

I could create a PR with my implementation (squashed into a single commit on a new branch), on the basis that it works today.  The alternative would be to rework the fill code more extensively, so that preserving point is handled closer to (or even within) `FillString`; this might entail creating some sort of variant of `transposeRegion` specifically for filling, but it would be more flexible later.

What do you think?

**Comment by japanoise** [comment]
> Namely, it assumes that the number of "words" (e.g., tokens separated by spaces or newlines) will be the same both before and after FillString

That should be a reasonable assumption for the moment, feel free to open the PR.

> if FillString were to be later enhanced to support source code comments then that would no longer work (e.g., for C99 style comments, the number of // "words" could change).

Yes, markdown blockquotes too. However, that would require messing with the major mode code which is some of the least developed in gomacs right now. That smells like a 2.x.x feature, and I'd rather we get another 1.x.x release or two out first (since gomacs has improved a fair bit since the last release). Once the larger issues (those that I've opened myself; the rendering bug #13, the custom syntax files #17, and especially zygomys #8) are taken care of and we're ready to roll up a 2.0.0 release, we can start thinking about extending major mode functionality.
