### ISSUE TITLE
find-file / C-x C-f moves cursor to begin of line on TAB completion

### ISSUE THREAD

**Issue by trembel** [japanoise/gomacs#48]
Whenever I use TAB completion inside "C-x C-f" (find-file), the cursor is moved to the begin of the line, which makes it impossible to easily navigate through folders in order to open a file (see attached gif).
![gomacs_find_file](https://user-images.githubusercontent.com/28383252/156980609-4162eae8-26a8-44d0-aaf9-5cf6d40bbd28.gif)

**Comment by ixtenu** [comment]
I've noticed this as well and I agree it's an issue.

The root cause is that tab completion uses the prompt callback and whenever the callback changes the contents of the minibuffer, the cursor position is reset to zero.  It wouldn't be hard to reset it to the end of the minibuffer.  A quick hack which does this:

```diff
diff --git a/input.go b/input.go
index a9c7559..8bd0d85 100644
--- a/input.go
+++ b/input.go
@@ -265,7 +265,9 @@ func EditDynamicWithCallback(defval, prompt string, refresh func(int, int), call
                        result := callback(buffer, key)
                        if result != buffer {
                                offset = 0
-                               buffer, buflen, bufpos, cursor = recalcBuffer(result)
+                               buffer, buflen, _, _ = recalcBuffer(result)
+                               bufpos = buflen
+                               cursor = termutil.RunewidthStr(buffer)
                        }
                }
        }
```

The callback is also called from other places within `EditDynamicWithCallback`.  I'm not sure if those other places should also place the cursor at the end of the minibuffer—would need to look at this at bit more which I don't have time for at the moment—but if they should, then `recalcBuffer` could be updated to return the end of the minibuffer as the 3rd and 4th return values, rather than updating its callers in  `EditDynamicWithCallback`.

**Comment by trembel** [comment]
Thanks, I'll try that as a quick fix for now.

**Comment by japanoise** [comment]
Wait, no, scratch that. The case where the text is *changed* should put it at the end, yes.
